DEFAULT_REGION = 'us-east-1'
DEFAULT_SCHEMA = 'aws_access_key'
NUM_OF_LIMIT = 100
MAX_EVENT_CHUNK_NUM = 20

EXCLUDE_EVENT_NAME = [
    'AddTags',
    'AddTagsToCertificate',
    'AddTagsToOnPremisesInstances',
    'AddTagsToResource',
    'AddTagsToStream',
    'AddTagsToVault',
    'AssociateTagOptionWithResource',
    'ChangeTagsForResource',
    'CreateDistributionWithTags',
    'CreateOrUpdateTags',
    'CreateStreamingDistributionWithTags',
    'CreateTagOption',
    'CreateTags',
    'DeleteAllTagsForDomain',
    'DeleteBucketTagging',
    'DeleteTagOption',
    'DeleteTags',
    'DeleteTagsForDomain',
    'PutBucketTagging',
    'PutImageTagMutability',
    'RemoveTags',
    'RemoveTagsFromCertificate',
    'RemoveTagsFromOnPremisesInstances',
    'RemoveTagsFromResource',
    'RemoveTagsFromStream',
    'RemoveTagsFromVault',
    'SetTagKeysState',
    'SetTagsFromResource',
    'Untag',
    'UntagCertificateAuthority',
    'UntagDeliveryStream',
    'UntagProject',
    'UntagQueue',
    'UntagResource',
    'UntagResources',
    'UpdateCertificateTag',
    'UpdateTagOption',
    'UpdateTagsForDomain',
    'ConsoleLogin',
    'CheckMfa'
]
